### ISSUE TITLE
`site disable` does not disable service

### ISSUE THREAD

**Issue by der-On** [small-tech/site.js#21] opened 2020-12-07 15:41 UTC
## Steps to reproduce

site.js version `20201107145233-16.0.1-891b972-linux/x64`
Ubuntu 20.04

1. I run `site enable` 
2. Site.js installs the service
3. I run `site disable`
4. I get the following output:    
```
   🧙    ❨site.js❩ Root privileges required.
   ✨    ❨site.js❩ Starting privileged process…
```
5. Site.js service is still running.

**Comment by aral** [comment] 2020-12-08 14:20
@der-On Thank you for reporting this. I know what the issue is and I’m now tracking it here: https://source.small-tech.org/site.js/app/-/issues/253

It’ll be fixed in the next update (this week).

**Comment by aral** [comment] 2020-12-28 18:31
This was fixed in the last release. Closing

**Closed by aral** 2020-12-28 18:31 UTC
